 // autogenerated by cargo-stylus
#include "Etherra.h"

// Iterate through the registry to find the function with the matching signature
ArbResult call_function(FunctionRegistry *registry, uint8_t registry_size, uint32_t signature, uint8_t *input, size_t len)
{
    for (uint8_t i = 0; i < registry_size; i++) // Loop until the sentinel is found
    {
        if (registry[i].signature == signature)
        return registry[i].function(input, len); // Call the function if signature matches
    }
    return _return_nodata(Success); // Return failure if function not found
}

uint32_t to_function_selector(const char *function_abi)
  {
    uint8_t result[16];
    native_keccak256((uint8_t *)function_abi, strlen(function_abi), result);
    return *((uint32_t *)result);
  }

int Etherra_entry(size_t argc) {

    uint8_t argv[argc];
    read_args(argv);

    FunctionRegistry registry[] = {
      {to_function_selector("checkOwnership(bytes32)"), checkOwnership},
      {to_function_selector("storeHash(bytes32)"), storeHash},
    };

    uint32_t signature = *((uint32_t *)argv);

    ArbResult res = call_function(registry, sizeof(registry) / sizeof(registry[0]), signature, argv + 4, argc - 4);

    return (write_result(res.output, res.output_len), res.status);
}


ENTRYPOINT(Etherra_entry)
